config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
  resources :comments
end
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user
	validates  :title, :body, presence: true
	before_create :title_case

	protected
		def title_case
			self.title = self.title.downcase.titleize
		end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])

	    @comment = @post.comments.new(comment_params)
	    @comment.user = current_user

	    if @comment.save
			redirect_to post_path(@post)
		else
			render :new
		end
	    

	end

	def destroy
		@post = Post.find(params[:post_id])
	    @comment = @post.comments.find(params[:id])
	    @comment.destroy
	    redirect_to post_path(@post)
	end

private
    def comment_params
    	params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
#index
	def index
		@posts = Post.all
	end
#show	
	def show
		@post = Post.find(params[:id])			
	end
#new
	def new
		@post = Post.new
	end
#edit	
	def edit
		@post = Post.find(params[:id])
	end
#update	
	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
    		redirect_to @post
  		else
   			render 'edit'
  		end
	end
#create
	def create
		@post = Post.new(post_params)
 		@post.user = current_user
 		if @post.save
			redirect_to @post
		else
			render :new
		end
	end
#delete
	def destroy
		  @post = Post.find(params[:id])
  @post.destroy
 
  redirect_to posts_path
		
	end






private
	def post_params
		params.require(:post).permit(:title, :body, :image)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div <% if comment.user == current_user %> style="background-color:lightgray" <%end%> >
<p>
  <strong>Commenter:</strong>
  <%= comment.user.email %>
</p>

 
<p>
  <strong> >> </strong>
  <%= comment.body %>
</p>
<p>

	<% if (current_user == comment.user || current_user == @post.user) %>
		<%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'REALLY?' } %>
    <% end %>
    <hr>

</p>
</div>



<!-- to wrap text in an html tag, select item and press: ctrl + shift + W -->

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Blog</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/yeti/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
        <li><%= link_to "Posts", posts_url %></li>
        <li><%= link_to "New Blog", new_post_path %></li>
      </ul>
      <!-- login and signup links -->
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/posts/edit.html.erb
<%if current_user == @post.user%>
	<h1>Edit</h1>
	<%= simple_form_for @post do |f| %>
	  <%= f.input :title %>
	  <%= f.input :body %>
	  <%= f.input :image %>
	  <%= f.button :submit %>
	<% end %>

<%else%>
	<p>you do not have permission to edit this blog</p>
<%end%>

app/views/posts/index.html.erb
<h1>Listing Blog Posts</h1>
 
 
 
  <% @posts.each do |post| %>
	<div class = "col-md-6">	
		<div class = "jumbotron" style = "background-color:rgb(250,250,250)">
			<strong>Poster:</strong><%= post.user.email %><br>
	 		<strong>Title: </strong><%= post.title %><br>
	 		<strong> > </strong> <%= truncate(post.body, length: 10) %><br>
	 		<%= link_to 'Show', post_path(post) %> 
	 		<% if current_user == post.user %>
	 			| <%= link_to 'Edit', edit_post_path(post) %> | 
	 			<%= link_to 'Remove', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
	 		<%end%><br>
	 		<%= image_tag(post.image, width:"100px") %>
	  	</div>
	</div> 
 	<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= simple_form_for @post do |f| %>
  
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :image %>
  <%= f.button :submit %>
<% end %>

app/views/posts/show.html.erb
	<div class = "col-md-8"><!-- post shower -->
		<h1>Blog Post ></h1>
		<p>
		  <strong>Title: </strong>
		  <%= @post.title %>
		</p>
		 
		<p>
		  <strong>Author:</strong>
		  <%= @post.user.email %>
		</p>
	
		<p>
		  <strong> > </strong>
		  <%= @post.body %>
		</p>
		<p>
		  <%= image_tag(@post.image, width:"500px") %>
		</p>

	</div>
<div class = "col-md-4">
	<!-- Comment shower -->
	<h3>Comments</h3>
	<%= render @post.comments %>
	
	
	<!-- comment adder -->
	
	<h2>Add a comment:</h2>
	<%= render 'comments/form' %>
</div>